config/routes.rb
Rails.application.routes.draw do
  get 'signet-out',  to: 'signouts#index'
  devise_for :users, except: :create, path: '', path_names: { sign_in: 'login', sign_out: 'signed-out' }
  resources :volunteer_help_requests do
    post 'take', to: 'volunteer_help_requests#take_in_progress'
    post 'finish', to: 'volunteer_help_requests#finish'
  end
  get 'help_requests_in_progress',  to: 'volunteer_help_requests#in_progress'
  root to: 'volunteer_help_requests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :volunteer_help_requests
end

app/models/volunteer_help_request.rb
class VolunteerHelpRequest < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  enum status: { pending: 0, in_progress: 1, finished: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/signouts_controller.rb
class SignoutsController < ApplicationController
  def index
  end
end

app/controllers/volunteer_help_requests_controller.rb
class VolunteerHelpRequestsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_volunteer_help_request, only: %i[ show edit update destroy ]

  # GET /volunteer_help_requests or /volunteer_help_requests.json
  def index
    @q = VolunteerHelpRequest.where.not(status: 'finished').ransack(params[:q])
    @volunteer_help_requests = @q.result(distict: true)
  end

  def in_progress
    @volunteer_help_requests = VolunteerHelpRequest.where(volounteer_id: current_user.id)
  end

  # GET /volunteer_help_requests/1 or /volunteer_help_requests/1.json
  def show
  end

  # GET /volunteer_help_requests/new
  def new
    @volunteer_help_request = VolunteerHelpRequest.new
  end

  # GET /volunteer_help_requests/1/edit
  def edit
  end

  # POST /volunteer_help_requests or /volunteer_help_requests.json
  def create
    @volunteer_help_request = current_user.volunteer_help_requests.new(volunteer_help_request_params)

    respond_to do |format|
      if @volunteer_help_request.save
        format.html { redirect_to volunteer_help_request_url(@volunteer_help_request), notice: "Volunteer help request was successfully created." }
        format.json { render :show, status: :created, location: @volunteer_help_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volunteer_help_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteer_help_requests/1 or /volunteer_help_requests/1.json
  def update
    respond_to do |format|
      if @volunteer_help_request.update(volunteer_help_request_params)
        format.html { redirect_to volunteer_help_request_url(@volunteer_help_request), notice: "Volunteer help request was successfully updated." }
        format.json { render :show, status: :ok, location: @volunteer_help_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volunteer_help_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def take_in_progress
    @volunteer_help_request = VolunteerHelpRequest.find(params[:volunteer_help_request_id])
    respond_to do |format|
      if  @volunteer_help_request.update(volounteer_id: current_user.id, status: 'in_progress')
        format.html { redirect_to volunteer_help_request_url(@volunteer_help_request), notice: "Volunteer help request was successfully took in progress" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def finish
    @volunteer_help_request = VolunteerHelpRequest.find(params[:volunteer_help_request_id])
    respond_to do |format|
      if  @volunteer_help_request.update(status: 'finished')
        format.html { redirect_to volunteer_help_request_url(@volunteer_help_request), notice: "Volunteer help request was successfully done" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteer_help_requests/1 or /volunteer_help_requests/1.json
  def destroy
    @volunteer_help_request.destroy

    respond_to do |format|
      format.html { redirect_to volunteer_help_requests_url, notice: "Volunteer help request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer_help_request
      @volunteer_help_request = VolunteerHelpRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volunteer_help_request_params
      params.require(:volunteer_help_request).permit(:title, :description, :deadline, :city, :status, photos: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signouts_helper.rb
module SignoutsHelper
end

app/helpers/volunteer_help_requests_helper.rb
module VolunteerHelpRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolounterPlatform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="navbar-text float-right mr-4">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-primary' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary'  %>
        <%= link_to "Took in progress", help_requests_in_progress_path, :class => 'btn btn-primary'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary'  %>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-primary'  %>
      <% end %>

    </div>
    <%= yield %>
  </body>
</html>

app/views/signouts/index.html.erb
<h2>Signed Out!</h2>

app/views/volunteer_help_requests/_form.html.erb
<%= form_with(model: volunteer_help_request, local: true) do |form| %>
  <% if volunteer_help_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volunteer_help_request.errors.count, "error") %> prohibited this volunteer_help_request from being saved:</h2>

      <ul>
        <% volunteer_help_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label 'Photos' %>
    <%= form.file_field :photos, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/volunteer_help_requests/edit.html.erb
<h1>Editing Volunteer Help Request</h1>

<%= render 'form', volunteer_help_request: @volunteer_help_request %>

<%= link_to 'Show', @volunteer_help_request %> |
<%= link_to 'Back', volunteer_help_requests_path %>

app/views/volunteer_help_requests/in_progress.html.erb
<p id="notice"><%= notice %></p>

<h1>Volunteer Help Requests I took in work</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>City</th>
      <th>Status</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteer_help_requests.each do |volunteer_help_request| %>
      <tr>
        <td><%= volunteer_help_request.title %></td>
        <td><%= volunteer_help_request.description %></td>
        <td><%= volunteer_help_request.deadline %></td>
        <td><%= volunteer_help_request.city %></td>
        <td><%= volunteer_help_request.status %></td>
        <td>
          <% volunteer_help_request.photos.each do |photo| %>
            <%= image_tag url_for(photo), style: 'width: 300px' %>
          <% end %>
        </td>
        <td><%= link_to 'Show', volunteer_help_request %></td>
        <% if VolounteerHelpRequestsPolicy.new(current_user, volunteer_help_request).update? %>
          <td><%= link_to 'Edit', edit_volunteer_help_request_path(volunteer_help_request) %></td>
        <% end %>
        <% if VolounteerHelpRequestsPolicy.new(current_user, volunteer_help_request).update? %>
          <td><%= link_to 'Destroy', volunteer_help_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/volunteer_help_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volunteer Help Requests</h1>

<%= search_form_for @q do |f| %>
  <%= f.search_field :title_or_description_cont, placeholder: "Search..." %>
  <%= f.submit "Search!" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>City</th>
      <th>Status</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteer_help_requests.each do |volunteer_help_request| %>
      <tr>
        <td><%= volunteer_help_request.title %></td>
        <td><%= volunteer_help_request.description %></td>
        <td><%= volunteer_help_request.deadline %></td>
        <td><%= volunteer_help_request.city %></td>
        <td><%= volunteer_help_request.status %></td>
        <td><%= volunteer_help_request.image %>
          <% volunteer_help_request.photos.each do |photo| %>
            <%= image_tag url_for(photo), style: 'width: 300px' %>
          <% end %>
        </td>
        <td><%= link_to 'Show', volunteer_help_request %></td>
        <td><%= link_to 'Edit', edit_volunteer_help_request_path(volunteer_help_request) %></td>
        <td><%= link_to 'Destroy', volunteer_help_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volunteer Help Request', new_volunteer_help_request_path %>

app/views/volunteer_help_requests/new.html.erb
<h1>New Volunteer Help Request</h1>

<%= render 'form', volunteer_help_request: @volunteer_help_request %>

<%= link_to 'Back', volunteer_help_requests_path %>

app/views/volunteer_help_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @volunteer_help_request.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @volunteer_help_request.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @volunteer_help_request.deadline %>
</p>

<p>
  <strong>City:</strong>
  <%= @volunteer_help_request.city %>
</p>

<p>
  <strong>Status:</strong>
  <%= @volunteer_help_request.status %>
</p>

<p>
  <strong>Images:</strong>
  <% @volunteer_help_request.photos.each do |photo| %>
    <%= image_tag url_for(photo), style: 'width: 300px' %>
  <% end %>
</p>

<% if VolounteerHelpRequestsPolicy.new(current_user, @volunteer_help_request).update? %>
  <%= link_to 'Edit', edit_volunteer_help_request_path(@volunteer_help_request) %>
<% end %>
<% if VolounteerHelpRequestsPolicy.new(current_user, @volunteer_help_request).take_in_progress? %>
  <%= link_to 'Take in progress', volunteer_help_request_take_path(volunteer_help_request_id: @volunteer_help_request.id), method: :post %>
<% end %>
<% if VolounteerHelpRequestsPolicy.new(current_user, @volunteer_help_request).finish? %>
  <%= link_to 'Finish', volunteer_help_request_finish_path(volunteer_help_request_id: @volunteer_help_request.id), method: :post %> |
<% end %>
<%= link_to 'Back', volunteer_help_requests_path %>